config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'

  get 'purchase/done'

  get 'card/new'

  get 'card/show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get 'jp/index'
  root 'jp#index'
  resources :products, only: [:show, :index, :create, :new] do
    resources :product_images, only: [:create, :new]
  end
  devise_scope :user do
    root 'users/registrations#new'
  end

  resources :users, only: [:edit] do
    member do
      get 'identification'
      get 'profile'
      get 'logout'
    end
  end

  resources :sold_products do
    member do
      get 'buy'
    end
    collection do
      post 'pay/:id' => 'sold_products#pay', as: 'pay'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bland.rb
class Bland < ApplicationRecord
    belongs_to :product
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :product
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :sub_category
end

app/models/product.rb
class Product < ApplicationRecord
    enum shipping_price: [['送料込み（出品者負担）'], ['着払い（購入者負担）'] ]
    enum shipping_way: [['未定'], ['クロネコヤマト'], ['ゆうパック'],['ゆうメール'] ]
    enum shipping_date: [['1~2日で発送'],['2~3日で発送'],['4~7日で発送'] ]
    enum size: [ ["XXS以下"], ["XS(SS)"], ["S"], ["M"], ["L"], ["XL"], ["2XL"], ["3XL"], ["4XL(5L)"], ["FREE SIZE"] ]
    enum product_quality: [ ["新品、未使用"], ["目立った傷や汚れなし"], ["やや傷や汚れあり"], ["傷や汚れあり"], ["全体的に状態が悪い"] ]
    enum product_status: [['未購入'],['購入済み'],['取引中'] ]


    belongs_to :user, optional: true
    has_one :bland
    has_one :region
    has_many :categorys
    has_many :images
    has_one :product_image
    has_many :comments
    accepts_nested_attributes_for :product_image
end

app/models/product_image.rb
class ProductImage < ApplicationRecord


    belongs_to :product, optional: true
    belongs_to :user, optional: true
    mount_uploader :image, ImageUploader
end

app/models/region.rb
class Region < ApplicationRecord
    belongs_to :product
end

app/models/reputation.rb
class Reputation < ApplicationRecord
    belongs_to :user
end

app/models/sold_product.rb
class SoldProduct < ApplicationRecord

  belongs_to :user
  belongs_to :product

end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reputations
  has_many :comments
  has_many :products
  has_many :sold_products
  has_many :cards
end

app/controllers/blands_controller.rb
class BlandsController < ApplicationController

  def index
  end

end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト',
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  end

  def create
  end

end

app/controllers/jp_controller.rb
class JpController < ApplicationController
  def index
    @products = Product.where("category_id=1").order("created_at DESC").page(params[:page]).per(4)
    @category = Category.all
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def edit
    @user = User.find(current_user.id)
  end

  def show
  end

  def update
  end

  def destroy
  end

  def identification
    @user = User.find(current_user.id)
  end

  def profile
    @user = User.find(current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSample45k
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = Gon::Base.render_data
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.2/css/all.css", :integrity => "sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay", :rel => "stylesheet"}/
    %link{:href => "https://use.fontawesome.com/releases/v5.6.1/css/all.css", :rel => "stylesheet"}/
  %body
    = yield

app/views/shared/_banner.html.haml
%aside.app-banner
  .app-banner__pc
    .content-left
      %h2.recomend-smartphone スマホでかんたんフリマアプリ
      %p.recomenddownload-text 今すぐ無料ダウンロード！
      .banner-link
        .banner-link__inner-left
          = image_tag 'mercari_icon.png', alt: 'mercari', class: 'mercari-icon'
        .banner-link__inner-right
          = link_to "/" do
            = image_tag 'Download_on_the_App_Store.svg', alt: 'appstore_link', class: 'appstore-icon'
          = link_to "/" do
            = image_tag 'google-play-badge.png', alt: 'googleplay', class: 'googleplay-icon'
    .banner-content-right
      = image_tag 'download_content_pc.png', alt: 'dlcontent', class: 'download-image'

app/views/shared/_footer.html.haml
%footer.global__footer
  %nav.footer__top
    .footer__top-cell
      %h2.cell__head メルカリについて
      %li.footer__top-list
        %a{:href => "/"} 会社概要（運営会社）
      %li.footer__top-list
        %a{:href => "/"} 採用情報
      %li.footer__top-list
        %a{:href => "/"} プレスリリース
      %li.footer__top-list
        %a{:href => "/"} 公式ブログ
      %li.footer__top-list
        %a{:href => "/"} メルカリロゴ利用ガイドライン
      %li.footer__top-icon
        %i.fab.f__Atwitter
      %li.footer__top-icon
        %i.fab.f__Afacebook
    .footer__top-cell
      %h2.cell__head ヘルプ＆ガイド
      %li.footer__top-list
        %a{:href => "/"} メルカリガイド
      %li.footer__top-list
        %a{:href => "/"} らくらくメルカリ便
      %li.footer__top-list
        %a{:href => "/"} ゆうゆうメルカリ便
      %li.footer__top-list
        %a{:href => "/"} 大型メルカリ便
      %li.footer__top-list
        %a{:href => "/"} 車体取引ガイド
      %li.footer__top-list
        %a{:href => "/"} メルカリあんしん・あんぜん宣言！
      %li.footer__top-list
        %a{:href => "/"} 偽ブランド品目滅への取り組み
      %li.footer__top-list
        %a{:href => "/"} メルカリボックス
    .footer__top-cell.width-expantion
      %h2.cell__head プライバシーと利用規約
      .inner
        %li.footer__top-list
          %a{:href => "/"} プライバシーポリシー
        %li.footer__top-list
          %a{:href => "/"} メルカリ利用規約
        %li.footer__top-list
          %a{:href => "/"} あんしんスマホサポート制度に関する利用特約
        %li.footer__top-list
          %a{:href => "/"} コンプライアンスポリシー
      .inner
        %li.footer__top-list
          %a{:href => "/"} 個人データの安全管理に係る基本方針
        %li.footer__top-list
          %a{:href => "/"} 特定商取引に関する表記
        %li.footer__top-list
          %a{:href => "/"} 資金決済法に基づく表示
        %li.footer__top-list
          %a{:href => "/"} 法令遵守と犯罪抑止のために
        %li.footer__top-list
          %a{:href => "/"} 返品・返金ポリシー
    .footer__top-cell.footer__lang
      %h2.cell__head 国
      %li.footer__top-list
        %a{:href => "/"} 日本
      %li.footer__top-list
        %a{:href => "/"} United States
  .footer__bottom
    .footer__logo
      %a{:href => "/"}
        = image_tag "logo-white.svg", size: "124x33", alt: "mercari"
    .copy__right
      © 2019 Mercari

app/views/shared/_footer_agreement.html.haml
.footer__agreement
  .footer__agreementwapper
    %a{:href => "/"} プライバシーポリシー
    %a{:href => "/"} メルカリ利用規約
    %a{:href => "/"} 特定商取引に関する表記
.footer__agreement--logo
  %a{:href => "/"}
    = image_tag 'mercari-icon.png', size: "105x74"
.copy__right
  © 2019 Mercari

app/views/shared/_header.html.haml
.header
  .header__top
    .header__top--left
      %a{:href => root_path}
        = image_tag "logo.svg", size: "134x36", alt: "ロゴ", class: "header-mercari-icon"
    .header__top--right
      %form{:action => "#", :method => "post"}
        %div
          %input{name: "search", placeholder: "何かお探しですか？", size: "50", type: "search", class: "product-search"}
            = fa_icon 'search', class: 'search-icon'
  .header__bottom
    .header__bottom--left
      .header__bottom--left--item-category
        %ul#category
          %li
            %i.fas.fa-list.header__bottom--left--itemcategory-list
            %a{:href => "#"} カテゴリーから探す
            %ul.child
              %li
                %a{:href => "#"} レディース
                %ul
                  %li.submenu
                    %a{:href => "#"} トップス
                    %ul
                      %li
                        %a{:href => "#"} Tシャツ/カットソー(半袖/袖なし)
                      %li
                        %a{:href => "#"} Tシャツ/カットソー(七分/長袖)
                      %li
                        %a{:href => "#"} シャツ/ブラウス(半袖/袖なし)
                      %li
                        %a{:href => "#"} シャツ/ブラウス(七分/長袖)
                      %li
                        %a{:href => "#"} ポロシャツ
                      %li
                        %a{:href => "#"} キャミソール
                      %li
                        %a{:href => "#"} タンクトップ
                      %li
                        %a{:href => "#"} ホルターネック
                      %li
                        %a{:href => "#"} ニット/セーター
                      %li
                        %a{:href => "#"} チュニック
                      %li
                        %a{:href => "#"} カーディガン/ボレロ
                      %li
                        %a{:href => "#"} アンサンブル
                      %li
                        %a{:href => "#"} ベスト/ジレ
                      %li
                        %a{:href => "#"} パーカー
                  %li
                    %a{:href => "#"} ジャケット/アウター
                  %li
                    %a{:href => "#"} パンツ
                  %li
                    %a{:href => "#"} スカート
                  %li
                    %a{:href => "#"} ワンピース
                  %li
                    %a{:href => "#"} 靴
                  %li
                    %a{:href => "#"} ルームウェア/パジャマ
                  %li
                    %a{:href => "#"} レッグウェア
                  %li
                    %a{:href => "#"} 帽子
                  %li
                    %a{:href => "#"} バッグ
                  %li
                    %a{:href => "#"} アクセサリー
                  %li
                    %a{:href => "#"} ヘアアクセサリー
                  %li
                    %a{:href => "#"} 小物
                  %li
                    %a{:href => "#"} 時計
              %li
                %a{:href => "#"} メンズ
              %li
                %a{:href => "#"} ベビー・キッズ
              %li
                %a{:href => "#"} インテリア・住まい・小物
              %li
                %a{:href => "#"} 本・音楽・ゲーム
              %li
                %a{:href => "#"} おもちゃ・ホビー・グッズ
              %li
                %a{:href => "#"} コスメ・香水・美容
              %li
                %a{:href => "#"} 家電・スマホ・カメラ
              %li
                %a{:href => "#"} スポーツ・メジャー
              %li
                %a{:href => "#"} ハンドメイド
              %li
                %a{:href => "#"} チケット
              %li
                %a{:href => "#"} 自転車・オートバイ
              %li
                %a{:href => "#"} その他
              %li
                %a{:href => "#"} カテゴリー一覧
      .header__bottom-left--item-brand
        %ul#bland
          %li
            %i.fas.fa-tag.header__bottom-left--itemcategory-brand
            %a{:href => "#"} ブランドから探す
            %ul.child
              %li
                %a{:href => "#"} シャネル
              %li
                %a{:href => "#"} ナイキ
              %li
                %a{:href => "#"} ルイヴィトン
              %li
                %a{:href => "#"} シュプリーム
              %li
                %a{:href => "#"} アディダス
              %li
                %a{:href => "#"} カテゴリー一覧
      - if user_signed_in?
        .header__bottom--right
          .header__bottom--right-block
            = fa_icon 'bell', class: 'bell-icon'
            = link_to 'お知らせ', root_path, class: "logged-in-button"
          .header__bottom--right-block
            = fa_icon 'check', class: 'check-icon'
            = link_to 'やることリスト', root_path, class: "logged-in-button"
          .header__bottom--right-block
            .ball-icon
            = link_to 'マイページ', destroy_user_session_path, method: "delete", class: "logged-in-button"


      - else
        .header__bottom--right
          = link_to '新規会員登録', new_user_registration_path, method: "get", class: "sign_in_btn"
          = link_to 'ログイン', user_session_path, method: "get", class: "new_user_btn"
        

app/views/shared/_icon-header.html.haml
.icon-header
  = image_tag 'icon.png', size: "213x54"

app/views/shared/_mypage_sidebar.html.haml
.mypage-sidebar
  .mypage-menu
    %ul.mypage-menu-list
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          マイページ
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          お知らせ
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          やることリスト
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          いいね！一覧
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          出品する
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          出品した商品−出品中
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          出品した商品−取引中
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          出品した商品−売却済み
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          購入した商品−取引中
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          購入した商品−過去の取引
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          ニュース一覧
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          評価一覧
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          ガイド
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          お問い合わせ
          %i.fas.fa-chevron-right
  .merpay-menu
    %h3.mypage-menu-head メルペイ
    %ul.mypage-menu-list
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          売上・振込申請
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          ポイント
          %i.fas.fa-chevron-right
  .settings
    %h3.mypage-menu-head 設定
    %ul.mypage-menu-list
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          プロフィール
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          支払い方法
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          メール/パスワード
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          本人情報
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "/", class: 'mypage-menu-link' do
          電話番号の確認
          %i.fas.fa-chevron-right
      %li.mypage-menu-list__item
        = link_to "logout_user_path(@users)", class: 'mypage-menu-link' do
          ログアウト
          %i.fas.fa-chevron-right

app/views/shared/_pickup.html.haml
- @products.each do |product|
  .pickup__items-item
    .pickup__items-item-picture
      = link_to product_path(product) do
        = image_tag "notepc.svg", size: "212x200", alt: "カテゴリ"
    .pickup__items-item-name
      = product.name
    .pickup__items-item-outline
      .pickup__items-item-outline_price
        = product.price
      .pickup__items-item-outline_likes
        = fa_icon 'heart', class: 'likes-icon'
    .pickup__items-item_tax
      （税込）

app/views/shared/_sell_btn.html.haml
= link_to new_product_path do
  .footer-sell-button
    .footer-sell-button__letter 出品
    %i.fas.fa-camera.footer-sell-button__icon

app/views/shared/_sub-footer.html.haml
.sub-footer
  .sub-footer__block プライバシーポリシー
  .sub-footer__block メルカリ利用規約
  .sub-footer__block 特定商取引に関する表記
  .sub-footer__icon= image_tag 'mercari-icon.png', size: "105x74"
  .sub-footer__copy-right © 2019 Mercari