config/routes.rb
Rails.application.routes.draw do
  get 'purchase/index'

  get 'purchase/done'

  get 'card/new'

  get 'card/show'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  get 'jp/index'
  root 'jp#index'
  resources :products, only: [:show, :index, :create, :new] do
    resources :product_images, only: [:create, :new]
  end
  devise_scope :user do
    root 'users/registrations#new'
  end

  resources :users, only: [:edit] do
    member do
      get 'identification'
      get 'profile'
      get 'logout'
    end
  end

  resources :sold_products do
    member do
      get 'buy'
    end
    collection do
      post 'pay/:id' => 'sold_products#pay', as: 'pay'
    end
  end

  resources :card, only: [:new, :show] do
    collection do
      post 'show', to: 'card#show'
      post 'pay', to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bland.rb
class Bland < ApplicationRecord
    belongs_to :product
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :product
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :sub_category
end

app/models/product.rb
class Product < ApplicationRecord
    enum shipping_price: [['送料込み（出品者負担）'], ['着払い（購入者負担）'] ]
    enum shipping_way: [['未定'], ['クロネコヤマト'], ['ゆうパック'],['ゆうメール'] ]
    enum shipping_date: [['1~2日で発送'],['2~3日で発送'],['4~7日で発送'] ]
    enum size: [ ["XXS以下"], ["XS(SS)"], ["S"], ["M"], ["L"], ["XL"], ["2XL"], ["3XL"], ["4XL(5L)"], ["FREE SIZE"] ]
    enum product_quality: [ ["新品、未使用"], ["目立った傷や汚れなし"], ["やや傷や汚れあり"], ["傷や汚れあり"], ["全体的に状態が悪い"] ]
    enum product_status: [['未購入'],['購入済み'],['取引中'] ]


    belongs_to :user, optional: true
    has_one :bland
    has_one :region
    has_many :categorys
    has_many :images
    has_one :product_image
    has_many :comments
    accepts_nested_attributes_for :product_image
end

app/models/product_image.rb
class ProductImage < ApplicationRecord


    belongs_to :product, optional: true
    belongs_to :user, optional: true
    mount_uploader :image, ImageUploader
end

app/models/region.rb
class Region < ApplicationRecord
    belongs_to :product
end

app/models/reputation.rb
class Reputation < ApplicationRecord
    belongs_to :user
end

app/models/sold_product.rb
class SoldProduct < ApplicationRecord

  belongs_to :user
  belongs_to :product

end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reputations
  has_many :comments
  has_many :products
  has_many :sold_products
  has_many :cards
end

app/controllers/blands_controller.rb
class BlandsController < ApplicationController

  def index
  end

end

app/controllers/card_controller.rb
class CardController < ApplicationController
  require "payjp"

  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      description: '登録テスト',
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
  end

  def create
  end

end

app/controllers/jp_controller.rb
class JpController < ApplicationController
  def index
    @products = Product.where("category_id=1").order("created_at DESC").page(params[:page]).per(4)
    @category = Category.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.where("category_id=1").order("created_at DESC").page(params[:page]).per(5)
  end

  def new
    @product = Product.new
    @product.build_product_image
  end

  def create
    product_params = params_int(set_product_params)
    @product = Product.new(product_params)
    binding.pry
    @product.save!
    redirect_to root_path, notice: '商品が出品されました'
  end

  def edit
  end

  def show
    @product = Product.find(params[:id])
    @exhibituser = User.find(@product.user_id)
    @category = Category.find(@product.category_id)
    @bland = Bland.find(@product.bland_id)
  end

  def update
  end

  def destroy
  end

  private

  def set_product_params
    params.require(:product).permit(:name,
                                    :description,
                                    :category_id,
                                    :sub_category_id,
                                    :item_id,
                                    :bland_id,
                                    :size,
                                    :product_quality,
                                    :shipping_price,
                                    :shipping_way,
                                    :shipping_place,
                                    :shipping_date,
                                    :price,
                                    product_image_attributes: [:id, :product_id, :image])
  end

  def params_int(product_params)
    product_params.each do |key,value|
      unless key == "name" || key == "description" || key == "product_image" || key == "image" || key == "product_image_attributes" || key == null
        product_params[key] = value.to_i
      end
    end
  end

end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  require 'payjp'

  def index
    @product = Product.find(params[:id])
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to controller: "card", action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  def pay
    @product = Product.find(params[:id])
    card = Card.where(user_id: current_user.id).first
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
    amount: @product.price,
    customer: card.customer_id,
    currency: 'jpy',
  )
    redirect_to done_purchase_index_path(@product, id: @product.id)
  end

  def done
    @product = Product.find(params[:id])
    @product.update_attribute(:purchasedflag, "1")
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def edit
    @user = User.find(current_user.id)
  end

  def show
  end

  def update
  end

  def destroy
  end

  def identification
    @user = User.find(current_user.id)
  end

  def profile
    @user = User.find(current_user.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/card/new.html.haml
= form_tag(pay_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %label カード番号
  = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
  %br
  %label 有効期限
  %select#exp_month{name: "exp_month", type: "text"}
    %option{value: ""} --
    %option{value: "1"}01
    %option{value: "2"}02
    %option{value: "3"}03
    %option{value: "4"}04
    %option{value: "5"}05
    %option{value: "6"}06
    %option{value: "7"}07
    %option{value: "8"}08
    %option{value: "9"}09
    %option{value: "10"}10
    %option{value: "11"}11
    %option{value: "12"}12
  %span 月/
  %select#exp_year{name: "exp_year", type: "text"}
    %option{value: ""} --
    %option{value: "2019"}19
    %option{value: "2020"}20
    %option{value: "2021"}21
    %option{value: "2022"}22
    %option{value: "2023"}23
    %option{value: "2024"}24
    %option{value: "2025"}25
    %option{value: "2026"}26
    %option{value: "2027"}27
    %option{value: "2028"}28
    %option{value: "2029"}29
  %span 年
  %br
  %label セキュリティコード
  = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
  #card_token
  = submit_tag "追加する", id: "token_submit"

app/views/card/show.html.haml
%label 登録クレジットカード情報
%br
= "**** **** **** " + @default_card_information.last4
%br
- exp_month = @default_card_information.exp_month.to_s
- exp_year = @default_card_information.exp_year.to_s.slice(2,3)
= exp_month + " / " + exp_year
= form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
  %input{ type: "hidden", name: "card_id", value: "" }
  %button 削除する

app/views/products/create.html.haml
= render partial: "shared/icon-header"
.content-wrapper
  = form_for @product do |f|
    .content-wrapper__header 商品情報を入力
    .upload-box
      .upload-container
        .upload-box__title 出品画像
        %span.essential-icon 必須
        .upload-box__description 最大10枚までアップロードできます
        .upload-box__upload-box ドラッグアンドドロップ<br>またはクリックしてファイルをアップロード
        = f.file_field :image, class: 'upload-box__upload-box'
    .content
      .content__name 商品名
      %span.essential-icon 必須
      = f.text_field :name, class: "content__form", placeholder: "商品名（必須40文字まで）"
      .content__name 商品の説明
      %span.essential-icon 必須
      = f.text_area :description, class: "content__textarea", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
    .detail
      .detail__title 商品の詳細
      .size-ajust
      .detail-container
        .detail__subtitle カテゴリー
        %span.essential-icon 必須
        = f.collection_select :category_id, Category.all, :id, :name, { include_blank: true, selected: '---'}, { class: "detail__pull-down" }
        %i.fas.fa-chevron-down.arrow-down
        - category_id = 1
        = f.collection_select :sub_category_id, SubCategory.where(category_id: category_id), :id, :name, { include_blank: true ,selected: '---'}, { class: "detail__pull-down" }
        %i.fas.fa-chevron-down.arrow-down
        - sub_category_id = 1
        = f.collection_select :item_id, Item.where(sub_category_id: sub_category_id), :id, :name, { include_blank: true , selected: '---'}, { class: "detail__pull-down" }
        %i.fas.fa-chevron-down.arrow-down
        .detail__subtitle ブランド
        %span.optional-icon 任意
        = f.text_field :bland, class: "detail__pull-down", placeholder: "例) シャネル"
        .detail__subtitle サイズ
        %span.essential-icon 必須
        = f.select :size, { "---": nil, "XXS以下": 1, "XS(SS)": 2, "S": 3, "M": 4, "L": 5, "L": 6, "XL": 7, "2XL": 8, "3XL": 9, "4XL(5L)": 10, "FREE SIZE": 11} , {} , { class: "detail__pull-down"}
        %i.fas.fa-chevron-down.arrow-down
        .detail__subtitle 商品の状態
        %span.essential-icon 必須
        = f.select :product_quality, { "---": nil, 新品、未使用: 1, 目立った傷や汚れなし: 2, やや傷や汚れあり: 3, 傷や汚れあり: 4, 全体的に状態が悪い: 5 }, {} ,{ class: "detail__pull-down" }
        %i.fas.fa-chevron-down.arrow-down
    .detail
      .detail__title 配送について
      .question-icon ?
      .detail-container
        .detail__subtitle 配送料の負担
        %span.essential-icon 必須
        = f.select :shipping_price, { "---": nil, "送料込み(出品者負担)": 1, "着払い(購入者負担)": 2} , {} , { class: "detail__pull-down"}
        %i.fas.fa-chevron-down.arrow-down
        .detail__subtitle 配送の方法
        %span.essential-icon 必須
        = f.select :shipping_way, { "---": nil, 未定: 1, クロネコヤマト: 2, ゆうパック: 3, ゆうメール: 4} , {} , { class: "detail__pull-down"}
        %i.fas.fa-chevron-down.arrow-down
        .detail__subtitle 発送元の地域
        %span.essential-icon 必須
        = f.select :shipping_place, { "---": nil, 北海道: 1, 東京: 2 }, {} , { class: "detail__pull-down"}
        %i.fas.fa-chevron-down.arrow-down
        .detail__subtitle 発送までの日数
        %span.essential-icon 必須
        = f.select :shipping_date, { "---": nil,"1~2日で発送": 1, "2~3日で発送": 2, "4~7日で発送": 3 }, {} , { class: "detail__pull-down"}
        %i.fas.fa-chevron-down.arrow-down
    .detail
      .detail__title 販売価格(300〜9,999,999)
      .question-icon ?
      .detail-container
        .detail-container__sub
          .detail__subtitle 価格
          %span.essential-icon 必須
          %span.yen ¥
          = f.text_field :price, class: "detail__price-input", placeholder: "例) 300"
        .detail-container__sub
          .detail__commission 販売手数料 (10%)
        .detail-container
          .detail__profit 販売利益
          .detail__profit--bar -
    .sell-box
      .sell-box__description--link
        = link_to "禁止されている出品"
      .sell-box__description--link 、
      .sell-box__description--link
        = link_to "行為"
      .sell-box__description--link を必ずご確認ください。
      .sell-box__description を必ずご確認ください。またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。<br>また、出品をもちまして加盟店規約に同意したことになります。
      =f.submit "出品する", class: "sell-box__sell-button"
      .sell-box__back-button もどる
    .content-wrapper__footer
= render partial: "shared/sub-footer"

app/views/products/exhibit.html.haml
= render "shared/header"
.product
  = render 'shared/mypage_sidebar'
  .product-container
    .product__title 正規品！COACH【コーチ】★★大きめ ミニシグネチャー ショルダーバッグ
    .product-wrapper
      .product__picture
        .product__picture--main
        .product__picture--sub-container
          .product__picture--sub
          .product__picture--sub
          .product__picture--sub
          .product__picture--sub
          .product__picture--sub
          .product__picture--sub
      .product__detail
        .product__detail--pack
          .product__detail--left 出品者
          .product__detail--right 〇〇さん
        .product__detail--pack
          .product__detail--left カテゴリー
          .product__detail--right レディース
        .product__detail--pack
          .product__detail--left ブランド
          .product__detail--right コーチ
        .product__detail--pack
          .product__detail--left 商品の状態
          .product__detail--right やや傷や汚れあり
        .product__detail--pack
          .product__detail--left 送料の負担
          .product__detail--right 送料込み（出品者負担）
        .product__detail--pack
          .product__detail--left 配送の方法
          .product__detail--right らくらくメルカリ便
        .product__detail--pack
          .product__detail--left 発送元地域
          .product__detail--right
            %a{:href => "#"} 兵庫県
        .product__detail--pack
          .product__detail--left 発送日の目安
          .product__detail--right 1~2日で発送
    .product__price-box
      .product__price ¥3,380
      %span.product__price--tax (税込)
      .product__price--shipping 送料込み
    .product__description ■商品ご覧頂き、誠にありがとうございます。※今だけ、フォロワーになって下さった方に、300円のお値引きサービス中！！私の商品検索は、#Boon・バッグ　検索してください。質問がありましたらコメントでよろしくお願いします！■ 商品説明 ■まずはプロフを確認してください☆■ 商品詳細 ■シンプルな落ち着いたお色味でどんな場面にも合い、どんな服にも合わせやすいお鞄です。使用感有！角擦れはございませんが多少の汚れはあります。内側はとても綺麗です使わなくなったのでどなたか使っていただける方お願いします。製造番号　H2K-9294【ブランド】COACH　コーチ【商品名】コーチ大き目シンプル【仕様】外ポケット１　内ポケット４【サイズ】縦：32横：31幅：7紐：130 多少調節可能＊他にも数多くの商品を出品しているので、ぜひご覧ください。＊複数購入、お取り置き(５日まで)もできるので、お気軽にお声がけくださいませ。＊中古品になりますので、予めご理解いただきますよう、お願い致します^_^※自宅保管、素人検品、素人寸法の誤差などにご理解がない方、神経質な方、完璧な物が欲しい方は購入お控えください。、お願い致します^_^※自宅保管、素人検品、素人寸法の誤差などにご理解がない方、神経質な方、完璧な物が欲しい方は購入お控えください。、お願い致します<br>#シンプル #かわいい #大き目 #かばん #バッグ
  .comment__wrapper
    .comment__sent-button 商品の編集
    .product__description-general or
    .comment__sent-button 出品を一旦停止する
    .comment__delete-button この商品を削除する
      = link_to '削除', blog_path(blog.id), method: "delete", remote: true, class: "delete_btn"

  .comment__wrapper
    .comment__container
      .comment__icon
      .comment__main
      .comment__time
    .comment__container
      .comment__icon
      .comment__main
      .comment__time
    .comment__container
      .comment__icon
      .comment__main
      .comment__time
    .comment__container
      .comment__icon
      .comment__main
      .comment__time
    .comment__note 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .comment__box
    .comment__sent-button コメントする
  = render 'shared/sell_btn'
=render "shared/banner"
=render "shared/footer"

app/views/products/index.html.haml
= render "shared/header"
#main_visual
  .main_visual_in
    %div
      = image_tag "banner-natsukashi.jpg", alt: "s1"
    %div
      = image_tag "banner-camp.jpg", alt: "s2"
    %div
      = image_tag "banner-natsukashi.jpg", alt: "s3"
.pickup
  %h2 商品一覧
  .pickup__items
    = render "shared/pickup"
  = paginate(@products)
.category
  .category__name カテゴリ名
  .category__namedescription 説明文
= render "shared/footer"
= render 'shared/sell_btn'

app/views/products/new.html.haml
= render partial: "shared/icon-header"
.content-wrapper
  = form_for @product do |f|
    .content-wrapper__header 商品情報を入力
    .upload-box
      .upload-container
        .upload-box__title 出品画像
        %span.essential-icon 必須
        .upload-box__description 最大10枚までアップロードできます
        .upload-box__upload-box ドラッグアンドドロップ<br>またはクリックしてファイルをアップロード
        = f.fields_for :product_image do |ff|
          = ff.file_field :image, class: 'upload-box__upload-box'
    .content
      .content__name 商品名
      %span.essential-icon 必須
      = f.text_field :name, class: "content__form", placeholder: "商品名（必須40文字まで）"
      .content__name 商品の説明
      %span.essential-icon 必須
      = f.text_area :description, class: "content__textarea", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
    .detail
      .detail__title 商品の詳細
      .size-ajust
      .detail-container
        .detail-container-pack
          .detail__subtitle カテゴリー
          %span.essential-icon 必須
          = f.collection_select :category_id, Category.all, :id, :name, { include_blank: true, selected: '---'}, { class: "detail__pull-down" }
          %i.fas.fa-chevron-down.arrow-down
          - category_id = 1
          = f.collection_select :sub_category_id, SubCategory.where(category_id: category_id), :id, :name, { include_blank: true ,selected: '---'}, { class: "detail__pull-down" }
          %i.fas.fa-chevron-down.arrow-down
          - sub_category_id = 1
          = f.collection_select :item_id, Item.where(sub_category_id: sub_category_id), :id, :name, { include_blank: true , selected: '---'}, { class: "detail__pull-down" }
          %i.fas.fa-chevron-down.arrow-down
        .detail-container-pack
          .detail__subtitle ブランド
          %span.optional-icon 任意
          = f.text_field :bland_id, class: "detail__pull-down", placeholder: "例) シャネル"
        .detail-container-pack
          .detail__subtitle サイズ
          %span.essential-icon 必須
          = f.select :size, { "---": nil, "XXS以下": 1, "XS(SS)": 2, "S": 3, "M": 4, "L": 5, "L": 6, "XL": 7, "2XL": 8, "3XL": 9, "4XL(5L)": 10, "FREE SIZE": 11} , {} , { class: "detail__pull-down"}
          %i.fas.fa-chevron-down.arrow-down
        .detail-container-pack
          .detail__subtitle 商品の状態
          %span.essential-icon 必須
          = f.select :product_quality, { "---": nil, "新品、未使用": 1, "目立った傷や汚れなし": 2, "やや傷や汚れあり": 3, "傷や汚れあり": 4, "全体的に状態が悪い": 5}, {} ,{ class: "detail__pull-down" }
          %i.fas.fa-chevron-down.arrow-down
    .detail
      .detail__title 配送について
      .question-icon ?
      .detail-container
        .detail-container-pack
          .detail__subtitle 配送料の負担
          %span.essential-icon 必須
          = f.select :shipping_price, { "---": nil, "送料込み(出品者負担)": 1, "着払い(購入者負担)": 2} , {} , { class: "detail__pull-down"}
          %i.fas.fa-chevron-down.arrow-down

        .detail-container-pack
          .detail__subtitle 配送の方法
          %span.essential-icon 必須
          = f.select :shipping_way, { "---": nil, 未定: 1, クロネコヤマト: 2, ゆうパック: 3, ゆうメール: 4} , {} , { class: "detail__pull-down"}
          %i.fas.fa-chevron-down.arrow-down

        .detail-container-pack
          .detail__subtitle 発送元の地域
          %span.essential-icon 必須
          = f.select :shipping_place, { "---": nil, 北海道: 1, 東京: 2 }, {} , { class: "detail__pull-down"}
          %i.fas.fa-chevron-down.arrow-down

        .detail-container-pack
          .detail__subtitle 発送までの日数
          %span.essential-icon 必須
          = f.select :shipping_date, { "---": nil,"1~2日で発送": 1, "2~3日で発送": 2, "4~7日で発送": 3 }, {} , { class: "detail__pull-down"}
          %i.fas.fa-chevron-down.arrow-down

    .detail
      .detail__title 販売価格(300〜9,999,999)
      .question-icon ?
      .detail-container
        .detail-container__sub
          .detail__subtitle 価格
          %span.essential-icon 必須
          %span.yen ¥
          = f.text_field :price, class: "detail__price-input", placeholder: "例) 300"
        .detail-container__sub
          .detail__commission 販売手数料 (10%)
        .detail-container
          .detail__profit 販売利益
          .detail__profit--bar -
    .sell-box
      .sell-box__description--link
        = link_to "禁止されている出品"
      .sell-box__description--link 、
      .sell-box__description--link
        = link_to "行為"
      .sell-box__description--link を必ずご確認ください。
      .sell-box__description を必ずご確認ください。またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。<br>また、出品をもちまして加盟店規約に同意したことになります。
      =f.submit "出品する", class: "sell-box__sell-button"
      .sell-box__back-button もどる
    .content-wrapper__footer
= render partial: "shared/sub-footer"

app/views/products/show.html.haml
= render "shared/header"
.product
  = render 'shared/mypage_sidebar'
  .product-container
    .product__title
      = @product.name
    .product-wrapper
      .product__picture
        .product__picture--main
        .product__picture--sub-container
          .product__picture--sub
          .product__picture--sub
          .product__picture--sub
          .product__picture--sub
          .product__picture--sub
          .product__picture--sub
      .product__detail
        .product__detail--pack
          .product__detail--left 出品者
          .product__detail--right
            = @exhibituser.kanji_name
        .product__detail--pack
          .product__detail--left カテゴリー
          .product__detail--right
            = @category.name
        .product__detail--pack
          .product__detail--left ブランド
          .product__detail--right
            = @bland.name
        .product__detail--pack
          .product__detail--left 商品の状態
          .product__detail--right
            = @product.product_quality
        .product__detail--pack
          .product__detail--left 送料の負担
          .product__detail--right
            = @product.price
        .product__detail--pack
          .product__detail--left 配送の方法
          .product__detail--right
            = @product.shipping_way[0]
        .product__detail--pack
          .product__detail--left 発送元地域
          .product__detail--right
            = @product.shipping_place
        .product__detail--pack
          .product__detail--left 発送日の目安
          .product__detail--right
            = @product.shipping_date[0]
    .product__price-box
      .product__price
        = "¥" + @product.price.to_s + "-"
      %span.product__price--tax (税込)
      .product__price--shipping 送料込み
    - if @product.purchasedflag == '0' || @product.purchasedflag == nil
      .product__action-button--notpurchased
        = link_to "購入画面に進む", buy_sold_product_path
    - else
      .product__action-button--purchased 売り切れました
    .product__description
      = @product.description
    .button-wrapper
      .good-button
        .good-button__heart
          %i.far.fa-heart.good-button__icon
        .good-button__letter いいね！
        .good-button__count 4
      .report-button
        %i.far.fa-flag.report-button__icon
        .report-button__letter 不適切な商品の報告
      .about-safty
        %i.fas.fa-lock.about-safty__icon
        .about-safty__letter あんしん・あんぜんのへの取り組み
  .comment__wrapper
    .comment__container
      .comment__icon
      .comment__main
      .comment__time
    .comment__container
      .comment__icon
      .comment__main
      .comment__time
    .comment__container
      .comment__icon
      .comment__main
      .comment__time
    .comment__container
      .comment__icon
      .comment__main
      .comment__time
    .comment__note 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
    .comment__box
    .comment__sent-button コメントする
  .product-link
    .product-link__right
      .product-link__name マフラー
      %span.product-link__right-arrow >
    .product-link__left
      %span.product-link__left-arrow <
      .product-link__name 靴下
  .sns-icon
    .sns-icon__wrapper
      = image_tag "facebook-icon.png", size: "44x44", class: "sns-icon__image"
      = image_tag "twitter-icon.png", size: "44x44", class: "sns-icon__image"
      = image_tag "pintarest-icon.png", size: "44x44", class: "sns-icon__image"
  .product__title 〇〇さんのその他の出品
  .other-product_container
  .other-product__container
  .other-product__container
  .other-product__container
  .other-product__container
  .other-product__container
  .other-product__container
  .product__title 〇〇その他の商品
  .other-product__container
  .other-product__container
  .other-product__container
  .other-product__container
  .other-product__container
  .other-product__container
  .other-product__container
  = render 'shared/sell_btn'
=render "shared/banner"
=render "shared/footer"